/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses/{analysis_id}/apply-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one review-form submission to an analysis
         * @description `201`: both branches create an immutable record and neither mutates one.
         *
         *     `application_id` is in the body rather than inferred from the analysis. The
         *     client states which Application it believes it is deciding for, and a
         *     mismatch is a `412` naming the broken lineage instead of a decision landing
         *     silently on another Application's analysis.
         */
        post: operations["apply_analysis_decisions_api_v1_analyses__analysis_id__apply_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/selection-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a replacement SelectionPlan for an analysis
         * @description `201` and the plan itself: the deterministic form is synchronous (§13).
         *
         *     The AI `propose_selection_plan` mode is the same route answering `202` with
         *     a `Location`, decided per request rather than per route, which is why the
         *     shared acceptance helper sets its own status.
         */
        post: operations["create_selection_plan_api_v1_analyses__analysis_id__selection_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create an application and its first immutable job snapshot */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/duplicate-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check for possible duplicate applications */
        post: operations["duplicate_check_api_v1_applications_duplicate_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an application and its active preparation state */
        get: operations["application_detail_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze one exact job snapshot
         * @description `202` and a `Location`: analysis is a durable Operation (§13).
         *
         *     NeedsReview is not an error here or anywhere else. An analysis that needs a
         *     decision is a *successful* Operation whose JobAnalysis and initial
         *     SelectionPlan were both committed; what needs deciding is reported by the
         *     Application's review reasons, and is resolved through
         *     `POST /analyses/{id}/apply-decisions`.
         */
        post: operations["create_analysis_api_v1_applications__application_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered artifact metadata for an application */
        get: operations["artifact_versions_api_v1_applications__application_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an application without deleting its history */
        post: operations["close_application_api_v1_applications__application_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the latest decision record for an application */
        get: operations["latest_decision_api_v1_applications__application_id__decision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/job-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new immutable job snapshot */
        post: operations["create_job_snapshot_api_v1_applications__application_id__job_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/working-draft/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate the active working draft from an exact analysis and plan
         * @description `202` and a `Location`: generation is a durable Operation (§14).
         *
         *     Both sources are named by the client. The Operation freezes them, so an
         *     analysis or plan that moves before activation fails the source check as
         *     `SOURCE_CHANGED` instead of silently drafting from something else.
         */
        post: operations["generate_working_draft_api_v1_applications__application_id__working_draft_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/working-draft/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the active working draft from an explicit analysis and plan
         * @description `202` and a `Location`: replacement is the draft Operation (§14).
         *
         *     Addressed to the Application, beside `generate`, because the Application is
         *     what owns the one active draft. The body still names the exact draft and the
         *     exact version being replaced, and a draft belonging to another Application
         *     is a `412` naming the broken lineage rather than a replacement landing
         *     somewhere nobody asked for.
         *
         *     Nothing is deleted first. The Operation commits the new document over the
         *     same active record, so a failure leaves the existing draft untouched, and
         *     `keep_previous` materializes the historical snapshot before any of it
         *     starts.
         */
        post: operations["replace_working_draft_api_v1_applications__application_id__working_draft_replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance identity and versions */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the progress of one durable Operation */
        get: operations["operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel queued work, or ask running work to stop
         * @description `200`, not `202`: cancellation is recorded synchronously.
         *
         *     Queued work is cancelled outright. Running work has
         *     `cancellation_requested_at` recorded and stops at its next checkpoint, so the
         *     returned status is truthfully still `running` - the request is what
         *     completed, not the Operation.
         */
        post: operations["cancel_operation_api_v1_operations__operation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a new Operation retrying a terminal one
         * @description `202` and a `Location` naming the *new* Operation.
         *
         *     The original is immutable and is not touched. Only a terminal Operation can
         *     be retried; retrying a live one is a `409`.
         */
        post: operations["retry_operation_api_v1_operations__operation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/working-drafts/{working_draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one working draft and its ETag
         * @description `200` plus an `ETag` built from `edit_version` and `content_hash` (§20).
         */
        get: operations["read_working_draft_api_v1_working_drafts__working_draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Autosave one structured patch against an exact draft version
         * @description `200` and the new `ETag`; a mismatch is `409` and changes nothing (§14).
         *
         *     The header is parsed into the two arguments the command declares rather
         *     than handed through as a string, so the application layer is never asked to
         *     understand an HTTP header.
         */
        patch: operations["update_working_draft_api_v1_working_drafts__working_draft_id__patch"];
        trace?: never;
    };
    "/api/v1/working-drafts/{working_draft_id}/apply-selection-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-select facts deterministically and rebuild the draft
         * @description `201`: the change creates an immutable SelectionPlan (§14, §22).
         *
         *     A draft carrying manual wording is refused with a `412` naming the
         *     regeneration commands, because a deterministic rebuild would replace the
         *     user's sentences with the engine's.
         */
        post: operations["apply_selection_change_api_v1_working_drafts__working_draft_id__apply_selection_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/working-drafts/{working_draft_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve exactly the content one ValidationRun passed
         * @description `201`: approval creates the immutable ApprovedRevision (§15, §22).
         *
         *     The same key with the same payload returns the same revision; the same key
         *     with a different draft, version, run, or content hash is
         *     `409 IDEMPOTENCY_KEY_REUSED`.
         */
        post: operations["approve_working_draft_api_v1_working_drafts__working_draft_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/working-drafts/{working_draft_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive the draft as an immutable historical snapshot
         * @description `200`: the snapshot is registered before the active pointer is cleared.
         */
        post: operations["archive_working_draft_api_v1_working_drafts__working_draft_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/working-drafts/{working_draft_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate one exact working draft version
         * @description `200` whether or not it passed: a failed validation is an outcome (§22).
         *
         *     Only a validator that could not execute is an error, and that surfaces as
         *     `500`/`503` from the application taxonomy rather than as a report nobody
         *     produced.
         */
        post: operations["validate_working_draft_api_v1_working_drafts__working_draft_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisDecisionsResponse
         * @description Which analysis is in force after the decision, and whether it is a new one.
         *
         *     `job_analysis_id` names the analysis the client should work from now: the
         *     new one when the decision changed meaning, the original when only the fact
         *     overlay moved. `created_analysis` is what tells the two apart.
         */
        AnalysisDecisionsResponse: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Application Id */
            application_id: string;
            /** Created Analysis */
            created_analysis: boolean;
            /** Job Analysis Id */
            job_analysis_id: string;
            plan: components["schemas"]["SelectionPlanResponse"];
            /** Selection Plan Id */
            selection_plan_id: string;
        };
        /** ApplicationDetailResponse */
        ApplicationDetailResponse: {
            /** Active Analysis Id */
            active_analysis_id?: string | null;
            /** Active Job Snapshot Id */
            active_job_snapshot_id: string;
            active_operation?: components["schemas"]["OperationResponse"] | null;
            /** Active Selection Plan Id */
            active_selection_plan_id?: string | null;
            /** Active Working Draft Id */
            active_working_draft_id?: string | null;
            application: components["schemas"]["ApplicationResponse"];
            /** Available Actions */
            available_actions: string[];
            /** Blocked Actions */
            blocked_actions: components["schemas"]["BlockedActionResponse"][];
            latest_analysis?: components["schemas"]["JobAnalysisResponse"] | null;
            /** Latest Approved Revision Id */
            latest_approved_revision_id?: string | null;
            /** Latest Ready Revision Id */
            latest_ready_revision_id?: string | null;
            latest_snapshot: components["schemas"]["JobSnapshotResponse"];
            /** Newer Draft In Progress */
            newer_draft_in_progress: boolean;
            /** Preparation State */
            preparation_state: string;
            /** Primary Stale Reason */
            primary_stale_reason?: string | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /** Recruitment Status */
            recruitment_status: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReasonResponse"][];
            /** Stale Reasons */
            stale_reasons: components["schemas"]["ReasonResponse"][];
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Warnings */
            warnings: components["schemas"]["WarningResponse"][];
            /** Working Draft State */
            working_draft_state: string;
        };
        /** ApplicationListItemResponse */
        ApplicationListItemResponse: {
            /** Active Analysis Id */
            active_analysis_id?: string | null;
            /** Active Job Snapshot Id */
            active_job_snapshot_id: string;
            active_operation?: components["schemas"]["OperationResponse"] | null;
            /** Active Selection Plan Id */
            active_selection_plan_id?: string | null;
            /** Active Working Draft Id */
            active_working_draft_id?: string | null;
            /** Available Actions */
            available_actions: string[];
            /** Blocked Actions */
            blocked_actions: components["schemas"]["BlockedActionResponse"][];
            /** Classification Confidence */
            classification_confidence?: number | null;
            /** Company */
            company: string;
            /** Created At */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Fit Level */
            fit_level?: string | null;
            /** Id */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Contact Date */
            last_contact_date?: string | null;
            /** Latest Approved Revision Id */
            latest_approved_revision_id?: string | null;
            /** Latest Ready Revision Id */
            latest_ready_revision_id?: string | null;
            /** Newer Draft In Progress */
            newer_draft_in_progress: boolean;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Normalized Role */
            normalized_role?: string | null;
            /** Notes */
            notes: string;
            /** Preparation State */
            preparation_state: string;
            /** Primary Stale Reason */
            primary_stale_reason?: string | null;
            /** Profile */
            profile?: string | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /** Recruitment Status */
            recruitment_status: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReasonResponse"][];
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Stale Reasons */
            stale_reasons: components["schemas"]["ReasonResponse"][];
            /** Target Role */
            target_role: string;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Track */
            track?: string | null;
            /** Updated At */
            updated_at: string;
            /** Warnings */
            warnings: components["schemas"]["WarningResponse"][];
            /** Working Draft State */
            working_draft_state: string;
        };
        /** ApplicationListResponse */
        ApplicationListResponse: {
            /** Items */
            items: components["schemas"]["ApplicationListItemResponse"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /** Classification Confidence */
            classification_confidence?: number | null;
            /** Company */
            company: string;
            /** Created At */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Fit Level */
            fit_level?: string | null;
            /** Id */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Contact Date */
            last_contact_date?: string | null;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Normalized Role */
            normalized_role?: string | null;
            /** Notes */
            notes: string;
            /** Profile */
            profile?: string | null;
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Track */
            track?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ApplyAnalysisDecisionsRequest */
        ApplyAnalysisDecisionsRequest: {
            /**
             * Accept Low Fit
             * @default false
             */
            accept_low_fit: boolean;
            /** Application Id */
            application_id: string;
            /** Emphasis Override */
            emphasis_override?: string | null;
            /**
             * Excluded Fact Ids
             * @default []
             */
            excluded_fact_ids: string[];
            /** Language Override */
            language_override?: string | null;
            /**
             * Pinned Fact Ids
             * @default []
             */
            pinned_fact_ids: string[];
            /** Profile Override */
            profile_override?: string | null;
            /** Track Override */
            track_override?: string | null;
        };
        /**
         * ApplySelectionChangeRequest
         * @description The user's explicit fact decisions for a deterministic re-selection.
         *
         *     Two lists, not three, on the same reasoning as the analysis review form:
         *     `selected` is what the resulting plan reports, and explicit inclusion is a
         *     pin.
         */
        ApplySelectionChangeRequest: {
            /**
             * Excluded Fact Ids
             * @default []
             */
            excluded_fact_ids: string[];
            /** Expected Edit Version */
            expected_edit_version: number;
            /**
             * Pinned Fact Ids
             * @default []
             */
            pinned_fact_ids: string[];
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Application Id */
            application_id: string;
            /** Decision Record Id */
            decision_record_id: string;
            /** Manifest Artifact Version Id */
            manifest_artifact_version_id: string;
            /** Markdown Artifact Version Id */
            markdown_artifact_version_id: string;
            /** Revision Id */
            revision_id: string;
            /** Version */
            version: number;
        };
        /**
         * ApproveDraftRequest
         * @description Approval names the ValidationRun whose result it is relying on.
         *
         *     The run is not created here. Approval verifies that the run describes this
         *     exact draft version and content and that it passed; a run approval created
         *     for itself could only ever agree with approval.
         */
        ApproveDraftRequest: {
            /** Expected Edit Version */
            expected_edit_version: number;
            /** Validation Run Id */
            validation_run_id: string;
        };
        /** ArchivedWorkingDraftResponse */
        ArchivedWorkingDraftResponse: {
            /** Application Id */
            application_id: string;
            /** Artifact Version Id */
            artifact_version_id: string;
            /** Content Hash */
            content_hash: string;
            /** Edit Version */
            edit_version: number;
            /** Working Draft Id */
            working_draft_id: string;
        };
        /** ArtifactVersionResponse */
        ArtifactVersionResponse: {
            /** Approved At */
            approved_at?: string | null;
            /** Artifact Id */
            artifact_id: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Facts Version */
            facts_version?: string | null;
            /** Id */
            id: string;
            /** Job Snapshot Id */
            job_snapshot_id?: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Logical Name */
            logical_name: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Profile */
            profile?: string | null;
            /** Revision Id */
            revision_id?: string | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Track */
            track?: string | null;
            /** Version Number */
            version_number: number;
        };
        /** ArtifactVersionsResponse */
        ArtifactVersionsResponse: {
            /** Items */
            items: components["schemas"]["ArtifactVersionResponse"][];
        };
        /** BlockedActionResponse */
        BlockedActionResponse: {
            /** Action */
            action: string;
            /** Reasons */
            reasons: string[];
        };
        /**
         * ClaimPatchRequest
         * @description One claim's replacement content.
         *
         *     Free text with no fact behind it is accepted and saved as a pending claim
         *     carrying the reason it could not be authorized; it is never discarded.
         */
        ClaimPatchRequest: {
            /** Claim Id */
            claim_id: string;
            /**
             * Fact Ids
             * @default []
             */
            fact_ids: string[];
            /** Template Id */
            template_id?: string | null;
            /** Template Version */
            template_version?: string | null;
            /** Text */
            text?: string | null;
        };
        /** CloseApplicationResponse */
        CloseApplicationResponse: {
            /** Application Id */
            application_id: string;
            /** Current Status */
            current_status: string;
            /** Event Id */
            event_id?: string | null;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
        };
        /**
         * CreateAnalysisRequest
         * @description What `POST /applications/{id}/analyses` accepts.
         *
         *     `job_snapshot_id` is explicit: an analyze command that picked its own source
         *     could classify something other than what the user was looking at.
         */
        CreateAnalysisRequest: {
            /**
             * Accept Low Fit
             * @default false
             */
            accept_low_fit: boolean;
            /** Emphasis Override */
            emphasis_override?: string | null;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Language Override */
            language_override?: string | null;
            /**
             * Model
             * @default rules-v1
             */
            model: string;
            /** Profile Override */
            profile_override?: string | null;
            /**
             * Provider
             * @default deterministic
             */
            provider: string;
            /** Track Override */
            track_override?: string | null;
        };
        /** CreateApplicationRequest */
        CreateApplicationRequest: {
            /**
             * Acknowledged Duplicates
             * @default false
             */
            acknowledged_duplicates: boolean;
            /** Company */
            company: string;
            /** Job Text */
            job_text: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
        };
        /** CreateApplicationResponse */
        CreateApplicationResponse: {
            /** Application Id */
            application_id: string;
            /** Duplicate Matches */
            duplicate_matches: components["schemas"]["DuplicateMatchResponse"][];
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Warnings */
            warnings: string[];
        };
        /** CreateJobSnapshotRequest */
        CreateJobSnapshotRequest: {
            /** Job Text */
            job_text: string;
            /**
             * Source Metadata
             * @default {}
             */
            source_metadata: {
                [key: string]: unknown;
            };
            /** Source Url */
            source_url?: string | null;
        };
        /** CreateJobSnapshotResponse */
        CreateJobSnapshotResponse: {
            /** Application Id */
            application_id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
        };
        /** CreateSelectionPlanRequest */
        CreateSelectionPlanRequest: {
            /** Application Id */
            application_id: string;
            /**
             * Excluded Fact Ids
             * @default []
             */
            excluded_fact_ids: string[];
            /** Expected Candidate Context Hash */
            expected_candidate_context_hash?: string | null;
            /** Expected Profile Version */
            expected_profile_version?: string | null;
            /** Expected Selection Policy Version */
            expected_selection_policy_version?: string | null;
            /**
             * Pinned Fact Ids
             * @default []
             */
            pinned_fact_ids: string[];
        };
        /** CreateSelectionPlanResponse */
        CreateSelectionPlanResponse: {
            /** Application Id */
            application_id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            plan: components["schemas"]["SelectionPlanResponse"];
            /** Selection Plan Id */
            selection_plan_id: string;
        };
        /** DecisionRecordResponse */
        DecisionRecordResponse: {
            /** Application Id */
            application_id: string;
            /** Artifact Version Id */
            artifact_version_id?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Structured */
            structured: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /** DuplicateCheckRequest */
        DuplicateCheckRequest: {
            /** Company */
            company: string;
            /** Job Text */
            job_text: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
        };
        /** DuplicateCheckResponse */
        DuplicateCheckResponse: {
            /** Matches */
            matches: components["schemas"]["DuplicateMatchResponse"][];
        };
        /** DuplicateMatchResponse */
        DuplicateMatchResponse: {
            /** Application Id */
            application_id: string;
            /** Company */
            company: string;
            /** Matched On */
            matched_on: ("source_url" | "normalized_text" | "company_title")[];
            /** Target Role */
            target_role: string;
        };
        /**
         * GenerateWorkingDraftRequest
         * @description What `POST /applications/{id}/working-draft/generate` accepts.
         *
         *     Both source IDs are explicit. A generate that resolved the latest analysis
         *     and plan for itself could build from a plan the user has never seen -
         *     §5.4's fifth acceptance item is exactly that commands take explicit source
         *     IDs.
         */
        GenerateWorkingDraftRequest: {
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Selection Plan Id */
            selection_plan_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description What `cv web` probes to tell its own instance from a foreign process.
         *
         *     `installation_id` and `workspace_id` together answer "is the process on this
         *     port mine, and is it serving the Workspace I am about to open". The version
         *     surfaces are the §17 provenance set, reported so a client can refuse to talk
         *     to an instance it does not understand.
         */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Installation Id */
            installation_id: string;
            knowledge: components["schemas"]["KnowledgeVersions"];
            /** Product Version */
            product_version: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** JobAnalysisResponse */
        JobAnalysisResponse: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Application Id */
            application_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Version Number */
            version_number: number;
        };
        /** JobSnapshotResponse */
        JobSnapshotResponse: {
            /** Application Id */
            application_id: string;
            /** Captured At */
            captured_at: string;
            /** Content Hash */
            content_hash: string;
            /** Id */
            id: string;
            /** Job Text */
            job_text: string;
            /** Prior Snapshot Id */
            prior_snapshot_id?: string | null;
            /** Source Metadata */
            source_metadata: {
                [key: string]: unknown;
            };
            /** Source Url */
            source_url?: string | null;
            /** Version Number */
            version_number: number;
        };
        /** KnowledgeVersions */
        KnowledgeVersions: {
            /** Candidate Context */
            candidate_context: string;
            /** Emphasis Policies */
            emphasis_policies: string;
            /** Facts */
            facts: string;
            /** Facts Lifecycle */
            facts_lifecycle: string;
            /** Presentations */
            presentations: string;
            /** Profiles */
            profiles: string;
        };
        /**
         * OperationOutputResponse
         * @description One immutable output an Operation produced.
         *
         *     Existence and activation are separate (§11): a failed or cancelled Operation
         *     may own an output that was registered as inactive evidence, so `active` is
         *     reported rather than inferred from the status.
         */
        OperationOutputResponse: {
            /** Active */
            active: boolean;
            /** Output Id */
            output_id: string;
            /** Output Type */
            output_type: string;
        };
        /**
         * OperationResponse
         * @description The §11 Operation query fields, and nothing wider.
         *
         *     This mirrors `OperationView`, not `PersistedOperation`. The payload, the
         *     frozen sources, the lease, and the idempotency key stay inside the runner.
         *
         *     `message` is a safe progress line and `safe_failure_detail` a safe failure
         *     line; neither carries a path, a provider response, or a key. There is no
         *     percentage field, because the specification forbids fabricating one.
         */
        OperationResponse: {
            /** Application Id */
            application_id: string;
            /** Cancellation Requested At */
            cancellation_requested_at?: string | null;
            /** Created At */
            created_at: string;
            /** Failure Code */
            failure_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Operation Type */
            operation_type: string;
            /** Outputs */
            outputs: components["schemas"]["OperationOutputResponse"][];
            /** Phase */
            phase: string;
            /** Retry Of Operation Id */
            retry_of_operation_id?: string | null;
            /** Safe Failure Detail */
            safe_failure_detail?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ReasonResponse */
        ReasonResponse: {
            /** Allowed Resolution Actions */
            allowed_resolution_actions: string[];
            /** Code */
            code: string;
            /** Entity References */
            entity_references: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /**
         * ReplaceWorkingDraftRequest
         * @description Replacement names its own compatible analysis and plan (§14).
         *
         *     The route is `POST /applications/{id}/working-draft/replace`, so the path
         *     carries the Application and the body carries the draft. Both are explicit
         *     and neither is inferred from the other: the client states which draft of
         *     which Application it means, and a pair that does not match is a `412`.
         *
         *     `keep_previous` is the Keep decision: it materializes the immutable
         *     historical snapshot before the replacement is attempted.
         */
        ReplaceWorkingDraftRequest: {
            /** Expected Edit Version */
            expected_edit_version: number;
            /** Job Analysis Id */
            job_analysis_id: string;
            /**
             * Keep Previous
             * @default false
             */
            keep_previous: boolean;
            /** Selection Plan Id */
            selection_plan_id: string;
            /** Working Draft Id */
            working_draft_id: string;
        };
        /** SelectionChangeResponse */
        SelectionChangeResponse: {
            /** Application Id */
            application_id: string;
            /** Content Hash */
            content_hash: string;
            /** Edit Version */
            edit_version: number;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Selection Plan Id */
            selection_plan_id: string;
            /** Working Draft Id */
            working_draft_id: string;
        };
        /** SelectionPlanResponse */
        SelectionPlanResponse: {
            /** Application Id */
            application_id: string;
            /** Candidate Context Hash */
            candidate_context_hash: string;
            /** Candidate Context Version */
            candidate_context_version: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Profile Version */
            profile_version: string;
            /** Selection Policy Version */
            selection_policy_version: string;
            /** Track Emphasis Dependencies */
            track_emphasis_dependencies: {
                [key: string]: string;
            };
            /** Version Number */
            version_number: number;
        };
        /**
         * UpdateWorkingDraftRequest
         * @description The structured patch `PATCH /working-drafts/{id}` applies as one edit.
         */
        UpdateWorkingDraftRequest: {
            /** Claim Edits */
            claim_edits: components["schemas"]["ClaimPatchRequest"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationRunResponse
         * @description A ValidationRun as data. `passed=false` arrives as `200` (§22).
         */
        ValidationRunResponse: {
            /** Application Id */
            application_id: string;
            /** Content Hash */
            content_hash: string;
            /** Edit Version */
            edit_version: number;
            /** Passed */
            passed: boolean;
            /** Report */
            report: {
                [key: string]: unknown;
            };
            /** Validation Run Id */
            validation_run_id: string;
            /** Working Draft Id */
            working_draft_id: string;
        };
        /** WarningResponse */
        WarningResponse: {
            /** Code */
            code: string;
            /** Entity References */
            entity_references: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /** WorkingDraftResponse */
        WorkingDraftResponse: {
            /** Active */
            active: boolean;
            /** Application Id */
            application_id: string;
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string;
            /** Edit Version */
            edit_version: number;
            /** Id */
            id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Latest Validation Passed */
            latest_validation_passed?: boolean | null;
            /** Latest Validation Run Id */
            latest_validation_run_id?: string | null;
            /** Parent Revision Id */
            parent_revision_id?: string | null;
            /** Selection Plan Id */
            selection_plan_id: string;
            /** Source */
            source: {
                [key: string]: unknown;
            };
            /** Updated At */
            updated_at: string;
        };
        /**
         * WorkingDraftUpdateResponse
         * @description The new token, and which claims were saved as pending.
         */
        WorkingDraftUpdateResponse: {
            /** Application Id */
            application_id: string;
            /** Content Hash */
            content_hash: string;
            /** Edit Version */
            edit_version: number;
            /**
             * Pending Claim Ids
             * @default []
             */
            pending_claim_ids: string[];
            /** Selection Plan Id */
            selection_plan_id: string;
            /** Working Draft Id */
            working_draft_id: string;
        };
        /**
         * WorkingDraftVersionRequest
         * @description The exact version a command is addressed to.
         */
        WorkingDraftVersionRequest: {
            /** Expected Edit Version */
            expected_edit_version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apply_analysis_decisions_api_v1_analyses__analysis_id__apply_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyAnalysisDecisionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDecisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_selection_plan_api_v1_analyses__analysis_id__selection_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSelectionPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSelectionPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_check_api_v1_applications_duplicate_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_detail_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_applications__application_id__analyses_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_versions_api_v1_applications__application_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_application_api_v1_applications__application_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_decision_api_v1_applications__application_id__decision_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_snapshot_api_v1_applications__application_id__job_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_working_draft_api_v1_applications__application_id__working_draft_generate_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateWorkingDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_working_draft_api_v1_applications__application_id__working_draft_replace_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceWorkingDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_operation_api_v1_operations__operation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_operation_api_v1_operations__operation_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_working_draft_api_v1_working_drafts__working_draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkingDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_working_draft_api_v1_working_drafts__working_draft_id__patch: {
        parameters: {
            query?: never;
            header: {
                /** @description Required. The ETag returned by the matching working-draft read. A value that no longer describes the stored draft is a 409 and changes nothing. */
                "If-Match": string;
            };
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkingDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkingDraftUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_selection_change_api_v1_working_drafts__working_draft_id__apply_selection_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplySelectionChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SelectionChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_working_draft_api_v1_working_drafts__working_draft_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_working_draft_api_v1_working_drafts__working_draft_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkingDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedWorkingDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_working_draft_api_v1_working_drafts__working_draft_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                working_draft_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkingDraftVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
