/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses/{analysis_id}/apply-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one review-form submission to an analysis
         * @description `201`: both branches create an immutable record and neither mutates one.
         *
         *     `application_id` is in the body rather than inferred from the analysis. The
         *     client states which Application it believes it is deciding for, and a
         *     mismatch is a `412` naming the broken lineage instead of a decision landing
         *     silently on another Application's analysis.
         */
        post: operations["apply_analysis_decisions_api_v1_analyses__analysis_id__apply_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/selection-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a replacement SelectionPlan for an analysis
         * @description `201` and the plan itself: the deterministic form is synchronous (§13).
         *
         *     The AI `propose_selection_plan` mode is the same route answering `202` with
         *     a `Location`, decided per request rather than per route, which is why the
         *     shared acceptance helper sets its own status.
         */
        post: operations["create_selection_plan_api_v1_analyses__analysis_id__selection_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create an application and its first immutable job snapshot */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/duplicate-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check for possible duplicate applications */
        post: operations["duplicate_check_api_v1_applications_duplicate_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an application and its active preparation state */
        get: operations["application_detail_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze one exact job snapshot
         * @description `202` and a `Location`: analysis is a durable Operation (§13).
         *
         *     NeedsReview is not an error here or anywhere else. An analysis that needs a
         *     decision is a *successful* Operation whose JobAnalysis and initial
         *     SelectionPlan were both committed; what needs deciding is reported by the
         *     Application's review reasons, and is resolved through
         *     `POST /analyses/{id}/apply-decisions`.
         */
        post: operations["create_analysis_api_v1_applications__application_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered artifact metadata for an application */
        get: operations["artifact_versions_api_v1_applications__application_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an application without deleting its history */
        post: operations["close_application_api_v1_applications__application_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the latest decision record for an application */
        get: operations["latest_decision_api_v1_applications__application_id__decision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/job-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new immutable job snapshot */
        post: operations["create_job_snapshot_api_v1_applications__application_id__job_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance identity and versions */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the progress of one durable Operation */
        get: operations["operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel queued work, or ask running work to stop
         * @description `200`, not `202`: cancellation is recorded synchronously.
         *
         *     Queued work is cancelled outright. Running work has
         *     `cancellation_requested_at` recorded and stops at its next checkpoint, so the
         *     returned status is truthfully still `running` - the request is what
         *     completed, not the Operation.
         */
        post: operations["cancel_operation_api_v1_operations__operation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue a new Operation retrying a terminal one
         * @description `202` and a `Location` naming the *new* Operation.
         *
         *     The original is immutable and is not touched. Only a terminal Operation can
         *     be retried; retrying a live one is a `409`.
         */
        post: operations["retry_operation_api_v1_operations__operation_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisDecisionsResponse
         * @description Which analysis is in force after the decision, and whether it is a new one.
         *
         *     `job_analysis_id` names the analysis the client should work from now: the
         *     new one when the decision changed meaning, the original when only the fact
         *     overlay moved. `created_analysis` is what tells the two apart.
         */
        AnalysisDecisionsResponse: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Application Id */
            application_id: string;
            /** Created Analysis */
            created_analysis: boolean;
            /** Job Analysis Id */
            job_analysis_id: string;
            plan: components["schemas"]["SelectionPlanResponse"];
            /** Selection Plan Id */
            selection_plan_id: string;
        };
        /** ApplicationDetailResponse */
        ApplicationDetailResponse: {
            /** Active Analysis Id */
            active_analysis_id?: string | null;
            /** Active Job Snapshot Id */
            active_job_snapshot_id: string;
            active_operation?: components["schemas"]["OperationResponse"] | null;
            /** Active Selection Plan Id */
            active_selection_plan_id?: string | null;
            /** Active Working Draft Id */
            active_working_draft_id?: string | null;
            application: components["schemas"]["ApplicationResponse"];
            /** Available Actions */
            available_actions: string[];
            /** Blocked Actions */
            blocked_actions: components["schemas"]["BlockedActionResponse"][];
            latest_analysis?: components["schemas"]["JobAnalysisResponse"] | null;
            /** Latest Approved Revision Id */
            latest_approved_revision_id?: string | null;
            /** Latest Ready Revision Id */
            latest_ready_revision_id?: string | null;
            latest_snapshot: components["schemas"]["JobSnapshotResponse"];
            /** Newer Draft In Progress */
            newer_draft_in_progress: boolean;
            /** Preparation State */
            preparation_state: string;
            /** Primary Stale Reason */
            primary_stale_reason?: string | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /** Recruitment Status */
            recruitment_status: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReasonResponse"][];
            /** Stale Reasons */
            stale_reasons: components["schemas"]["ReasonResponse"][];
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Warnings */
            warnings: components["schemas"]["WarningResponse"][];
            /** Working Draft State */
            working_draft_state: string;
        };
        /** ApplicationListItemResponse */
        ApplicationListItemResponse: {
            /** Active Analysis Id */
            active_analysis_id?: string | null;
            /** Active Job Snapshot Id */
            active_job_snapshot_id: string;
            active_operation?: components["schemas"]["OperationResponse"] | null;
            /** Active Selection Plan Id */
            active_selection_plan_id?: string | null;
            /** Active Working Draft Id */
            active_working_draft_id?: string | null;
            /** Available Actions */
            available_actions: string[];
            /** Blocked Actions */
            blocked_actions: components["schemas"]["BlockedActionResponse"][];
            /** Classification Confidence */
            classification_confidence?: number | null;
            /** Company */
            company: string;
            /** Created At */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Fit Level */
            fit_level?: string | null;
            /** Id */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Contact Date */
            last_contact_date?: string | null;
            /** Latest Approved Revision Id */
            latest_approved_revision_id?: string | null;
            /** Latest Ready Revision Id */
            latest_ready_revision_id?: string | null;
            /** Newer Draft In Progress */
            newer_draft_in_progress: boolean;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Normalized Role */
            normalized_role?: string | null;
            /** Notes */
            notes: string;
            /** Preparation State */
            preparation_state: string;
            /** Primary Stale Reason */
            primary_stale_reason?: string | null;
            /** Profile */
            profile?: string | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /** Recruitment Status */
            recruitment_status: string;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReasonResponse"][];
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Stale Reasons */
            stale_reasons: components["schemas"]["ReasonResponse"][];
            /** Target Role */
            target_role: string;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Track */
            track?: string | null;
            /** Updated At */
            updated_at: string;
            /** Warnings */
            warnings: components["schemas"]["WarningResponse"][];
            /** Working Draft State */
            working_draft_state: string;
        };
        /** ApplicationListResponse */
        ApplicationListResponse: {
            /** Items */
            items: components["schemas"]["ApplicationListItemResponse"][];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /** Classification Confidence */
            classification_confidence?: number | null;
            /** Company */
            company: string;
            /** Created At */
            created_at: string;
            /** Current Status */
            current_status: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Fit Level */
            fit_level?: string | null;
            /** Id */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Contact Date */
            last_contact_date?: string | null;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Normalized Role */
            normalized_role?: string | null;
            /** Notes */
            notes: string;
            /** Profile */
            profile?: string | null;
            /** Source */
            source: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
            /** Track */
            track?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ApplyAnalysisDecisionsRequest */
        ApplyAnalysisDecisionsRequest: {
            /**
             * Accept Low Fit
             * @default false
             */
            accept_low_fit: boolean;
            /** Application Id */
            application_id: string;
            /** Emphasis Override */
            emphasis_override?: string | null;
            /**
             * Excluded Fact Ids
             * @default []
             */
            excluded_fact_ids: string[];
            /** Language Override */
            language_override?: string | null;
            /**
             * Pinned Fact Ids
             * @default []
             */
            pinned_fact_ids: string[];
            /** Profile Override */
            profile_override?: string | null;
            /** Track Override */
            track_override?: string | null;
        };
        /** ArtifactVersionResponse */
        ArtifactVersionResponse: {
            /** Approved At */
            approved_at?: string | null;
            /** Artifact Id */
            artifact_id: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string;
            /** Emphasis */
            emphasis?: string | null;
            /** Facts Version */
            facts_version?: string | null;
            /** Id */
            id: string;
            /** Job Snapshot Id */
            job_snapshot_id?: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Logical Name */
            logical_name: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Profile */
            profile?: string | null;
            /** Revision Id */
            revision_id?: string | null;
            /** Submitted At */
            submitted_at?: string | null;
            /** Track */
            track?: string | null;
            /** Version Number */
            version_number: number;
        };
        /** ArtifactVersionsResponse */
        ArtifactVersionsResponse: {
            /** Items */
            items: components["schemas"]["ArtifactVersionResponse"][];
        };
        /** BlockedActionResponse */
        BlockedActionResponse: {
            /** Action */
            action: string;
            /** Reasons */
            reasons: string[];
        };
        /** CloseApplicationResponse */
        CloseApplicationResponse: {
            /** Application Id */
            application_id: string;
            /** Current Status */
            current_status: string;
            /** Event Id */
            event_id?: string | null;
            /** Next Action */
            next_action?: string | null;
            /** Next Action Date */
            next_action_date?: string | null;
            /** Terminal Outcome */
            terminal_outcome?: string | null;
        };
        /**
         * CreateAnalysisRequest
         * @description What `POST /applications/{id}/analyses` accepts.
         *
         *     `job_snapshot_id` is explicit: an analyze command that picked its own source
         *     could classify something other than what the user was looking at.
         */
        CreateAnalysisRequest: {
            /**
             * Accept Low Fit
             * @default false
             */
            accept_low_fit: boolean;
            /** Emphasis Override */
            emphasis_override?: string | null;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Language Override */
            language_override?: string | null;
            /**
             * Model
             * @default rules-v1
             */
            model: string;
            /** Profile Override */
            profile_override?: string | null;
            /**
             * Provider
             * @default deterministic
             */
            provider: string;
            /** Track Override */
            track_override?: string | null;
        };
        /** CreateApplicationRequest */
        CreateApplicationRequest: {
            /**
             * Acknowledged Duplicates
             * @default false
             */
            acknowledged_duplicates: boolean;
            /** Company */
            company: string;
            /** Job Text */
            job_text: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
        };
        /** CreateApplicationResponse */
        CreateApplicationResponse: {
            /** Application Id */
            application_id: string;
            /** Duplicate Matches */
            duplicate_matches: components["schemas"]["DuplicateMatchResponse"][];
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Warnings */
            warnings: string[];
        };
        /** CreateJobSnapshotRequest */
        CreateJobSnapshotRequest: {
            /** Job Text */
            job_text: string;
            /**
             * Source Metadata
             * @default {}
             */
            source_metadata: {
                [key: string]: unknown;
            };
            /** Source Url */
            source_url?: string | null;
        };
        /** CreateJobSnapshotResponse */
        CreateJobSnapshotResponse: {
            /** Application Id */
            application_id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
        };
        /** CreateSelectionPlanRequest */
        CreateSelectionPlanRequest: {
            /** Application Id */
            application_id: string;
            /**
             * Excluded Fact Ids
             * @default []
             */
            excluded_fact_ids: string[];
            /** Expected Candidate Context Hash */
            expected_candidate_context_hash?: string | null;
            /** Expected Profile Version */
            expected_profile_version?: string | null;
            /** Expected Selection Policy Version */
            expected_selection_policy_version?: string | null;
            /**
             * Pinned Fact Ids
             * @default []
             */
            pinned_fact_ids: string[];
        };
        /** CreateSelectionPlanResponse */
        CreateSelectionPlanResponse: {
            /** Application Id */
            application_id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            plan: components["schemas"]["SelectionPlanResponse"];
            /** Selection Plan Id */
            selection_plan_id: string;
        };
        /** DecisionRecordResponse */
        DecisionRecordResponse: {
            /** Application Id */
            application_id: string;
            /** Artifact Version Id */
            artifact_version_id?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Structured */
            structured: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /** DuplicateCheckRequest */
        DuplicateCheckRequest: {
            /** Company */
            company: string;
            /** Job Text */
            job_text: string;
            /** Source Url */
            source_url?: string | null;
            /** Target Role */
            target_role: string;
        };
        /** DuplicateCheckResponse */
        DuplicateCheckResponse: {
            /** Matches */
            matches: components["schemas"]["DuplicateMatchResponse"][];
        };
        /** DuplicateMatchResponse */
        DuplicateMatchResponse: {
            /** Application Id */
            application_id: string;
            /** Company */
            company: string;
            /** Matched On */
            matched_on: ("source_url" | "normalized_text" | "company_title")[];
            /** Target Role */
            target_role: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description What `cv web` probes to tell its own instance from a foreign process.
         *
         *     `installation_id` and `workspace_id` together answer "is the process on this
         *     port mine, and is it serving the Workspace I am about to open". The version
         *     surfaces are the §17 provenance set, reported so a client can refuse to talk
         *     to an instance it does not understand.
         */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Installation Id */
            installation_id: string;
            knowledge: components["schemas"]["KnowledgeVersions"];
            /** Product Version */
            product_version: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** JobAnalysisResponse */
        JobAnalysisResponse: {
            /** Analysis */
            analysis: {
                [key: string]: unknown;
            };
            /** Application Id */
            application_id: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Snapshot Id */
            job_snapshot_id: string;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Version Number */
            version_number: number;
        };
        /** JobSnapshotResponse */
        JobSnapshotResponse: {
            /** Application Id */
            application_id: string;
            /** Captured At */
            captured_at: string;
            /** Content Hash */
            content_hash: string;
            /** Id */
            id: string;
            /** Job Text */
            job_text: string;
            /** Prior Snapshot Id */
            prior_snapshot_id?: string | null;
            /** Source Metadata */
            source_metadata: {
                [key: string]: unknown;
            };
            /** Source Url */
            source_url?: string | null;
            /** Version Number */
            version_number: number;
        };
        /** KnowledgeVersions */
        KnowledgeVersions: {
            /** Candidate Context */
            candidate_context: string;
            /** Emphasis Policies */
            emphasis_policies: string;
            /** Facts */
            facts: string;
            /** Facts Lifecycle */
            facts_lifecycle: string;
            /** Presentations */
            presentations: string;
            /** Profiles */
            profiles: string;
        };
        /**
         * OperationOutputResponse
         * @description One immutable output an Operation produced.
         *
         *     Existence and activation are separate (§11): a failed or cancelled Operation
         *     may own an output that was registered as inactive evidence, so `active` is
         *     reported rather than inferred from the status.
         */
        OperationOutputResponse: {
            /** Active */
            active: boolean;
            /** Output Id */
            output_id: string;
            /** Output Type */
            output_type: string;
        };
        /**
         * OperationResponse
         * @description The §11 Operation query fields, and nothing wider.
         *
         *     This mirrors `OperationView`, not `PersistedOperation`. The payload, the
         *     frozen sources, the lease, and the idempotency key stay inside the runner.
         *
         *     `message` is a safe progress line and `safe_failure_detail` a safe failure
         *     line; neither carries a path, a provider response, or a key. There is no
         *     percentage field, because the specification forbids fabricating one.
         */
        OperationResponse: {
            /** Application Id */
            application_id: string;
            /** Cancellation Requested At */
            cancellation_requested_at?: string | null;
            /** Created At */
            created_at: string;
            /** Failure Code */
            failure_code?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Operation Type */
            operation_type: string;
            /** Outputs */
            outputs: components["schemas"]["OperationOutputResponse"][];
            /** Phase */
            phase: string;
            /** Retry Of Operation Id */
            retry_of_operation_id?: string | null;
            /** Safe Failure Detail */
            safe_failure_detail?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ReasonResponse */
        ReasonResponse: {
            /** Allowed Resolution Actions */
            allowed_resolution_actions: string[];
            /** Code */
            code: string;
            /** Entity References */
            entity_references: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
        /** SelectionPlanResponse */
        SelectionPlanResponse: {
            /** Application Id */
            application_id: string;
            /** Candidate Context Hash */
            candidate_context_hash: string;
            /** Candidate Context Version */
            candidate_context_version: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Job Analysis Id */
            job_analysis_id: string;
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** Profile Version */
            profile_version: string;
            /** Selection Policy Version */
            selection_policy_version: string;
            /** Track Emphasis Dependencies */
            track_emphasis_dependencies: {
                [key: string]: string;
            };
            /** Version Number */
            version_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningResponse */
        WarningResponse: {
            /** Code */
            code: string;
            /** Entity References */
            entity_references: {
                [key: string]: string;
            };
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apply_analysis_decisions_api_v1_analyses__analysis_id__apply_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyAnalysisDecisionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDecisionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_selection_plan_api_v1_analyses__analysis_id__selection_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSelectionPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSelectionPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_check_api_v1_applications_duplicate_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_detail_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_applications__application_id__analyses_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_versions_api_v1_applications__application_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactVersionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_application_api_v1_applications__application_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_decision_api_v1_applications__application_id__decision_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_snapshot_api_v1_applications__application_id__job_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_operation_api_v1_operations__operation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_operation_api_v1_operations__operation_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional. A retry that reuses the key of an Operation which already exists returns that Operation instead of queueing a second attempt. Omitted, the boundary generates a key, exactly as the CLI does. */
                "Idempotency-Key"?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
