/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance identity and versions */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthResponse
         * @description What `cv web` probes to tell its own instance from a foreign process.
         *
         *     `installation_id` and `workspace_id` together answer "is the process on this
         *     port mine, and is it serving the Workspace I am about to open". The version
         *     surfaces are the §17 provenance set, reported so a client can refuse to talk
         *     to an instance it does not understand.
         */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Installation Id */
            installation_id: string;
            knowledge: components["schemas"]["KnowledgeVersions"];
            /** Product Version */
            product_version: string;
            /** Schema Version */
            schema_version: string;
            /** Status */
            status: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** KnowledgeVersions */
        KnowledgeVersions: {
            /** Candidate Context */
            candidate_context: string;
            /** Emphasis Policies */
            emphasis_policies: string;
            /** Facts */
            facts: string;
            /** Facts Lifecycle */
            facts_lifecycle: string;
            /** Presentations */
            presentations: string;
            /** Profiles */
            profiles: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
