"""sequence columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-25 13:53:41.904914
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEQUENCE_TABLES = (
    "audit_records",
    "fact_events",
    "recruitment_events",
    "submissions",
    "validation_runs",
)


def _create_sequence(table_name: str) -> None:
    op.execute(sa.schema.CreateSequence(sa.Sequence(f"{table_name}_seq_seq")))


def _drop_sequence(table_name: str) -> None:
    op.execute(sa.schema.DropSequence(sa.Sequence(f"{table_name}_seq_seq")))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in SEQUENCE_TABLES:
        _create_sequence(table_name)
    op.add_column(
        "audit_records",
        sa.Column(
            "seq",
            sa.BigInteger(),
            server_default=sa.text("nextval('audit_records_seq_seq')"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("idx_audit_records_application"), table_name="audit_records")
    op.create_index(
        "idx_audit_records_application",
        "audit_records",
        ["application_id", "occurred_at", "seq"],
        unique=False,
    )
    op.add_column(
        "fact_events",
        sa.Column(
            "seq",
            sa.BigInteger(),
            server_default=sa.text("nextval('fact_events_seq_seq')"),
            nullable=False,
        ),
    )
    op.add_column(
        "recruitment_events",
        sa.Column(
            "seq",
            sa.BigInteger(),
            server_default=sa.text("nextval('recruitment_events_seq_seq')"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("idx_recruitment_events_application"), table_name="recruitment_events")
    op.create_index(
        "idx_recruitment_events_application",
        "recruitment_events",
        ["application_id", "occurred_at", "seq"],
        unique=False,
    )
    op.add_column(
        "submissions",
        sa.Column(
            "seq",
            sa.BigInteger(),
            server_default=sa.text("nextval('submissions_seq_seq')"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("idx_submissions_application"), table_name="submissions")
    op.create_index(
        "idx_submissions_application",
        "submissions",
        ["application_id", "submitted_at", "seq"],
        unique=False,
    )
    op.add_column(
        "validation_runs",
        sa.Column(
            "seq",
            sa.BigInteger(),
            server_default=sa.text("nextval('validation_runs_seq_seq')"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validation_runs", "seq")
    op.drop_index("idx_submissions_application", table_name="submissions")
    op.create_index(
        op.f("idx_submissions_application"),
        "submissions",
        ["application_id", "submitted_at", "id"],
        unique=False,
    )
    op.drop_column("submissions", "seq")
    op.drop_index("idx_recruitment_events_application", table_name="recruitment_events")
    op.create_index(
        op.f("idx_recruitment_events_application"),
        "recruitment_events",
        ["application_id", "occurred_at", "id"],
        unique=False,
    )
    op.drop_column("recruitment_events", "seq")
    op.drop_column("fact_events", "seq")
    op.drop_index("idx_audit_records_application", table_name="audit_records")
    op.create_index(
        op.f("idx_audit_records_application"),
        "audit_records",
        ["application_id", "occurred_at", "id"],
        unique=False,
    )
    op.drop_column("audit_records", "seq")
    for table_name in reversed(SEQUENCE_TABLES):
        _drop_sequence(table_name)
    # ### end Alembic commands ###
