from __future__ import annotations

from typing import Any, Protocol

from ...domain.contracts.drafts import WorkingDraft
from ...domain.contracts.records import ApprovedRevision
from ...domain.contracts.selection import SelectionPlan
from ..operations import OperationView
from .transactions import ReadTransaction


class ApplicationProjectionReader(Protocol):
    """Database-only inputs for the API application projections."""

    def application(self, tx: ReadTransaction, application_id: str) -> dict[str, Any]: ...
    def applications(self, tx: ReadTransaction) -> list[dict[str, Any]]: ...
    def latest_snapshot(self, tx: ReadTransaction, application_id: str) -> dict[str, Any]: ...
    def snapshots(self, tx: ReadTransaction, application_id: str) -> list[dict[str, Any]]: ...
    def analyses(self, tx: ReadTransaction, application_id: str) -> list[dict[str, Any]]: ...
    def analysis(self, tx: ReadTransaction, analysis_id: str) -> dict[str, Any]: ...
    def selection_plan(self, tx: ReadTransaction, selection_plan_id: str) -> SelectionPlan: ...
    def latest_selection_plan(
        self, tx: ReadTransaction, application_id: str
    ) -> SelectionPlan | None: ...
    def working_draft(self, tx: ReadTransaction, working_draft_id: str) -> WorkingDraft: ...
    def active_working_draft(
        self, tx: ReadTransaction, application_id: str
    ) -> WorkingDraft | None: ...
    def approved_revisions(
        self, tx: ReadTransaction, application_id: str
    ) -> list[ApprovedRevision]: ...
    def approved_revision(self, tx: ReadTransaction, revision_id: str) -> ApprovedRevision: ...
    def latest_validation_for_working_draft(
        self, tx: ReadTransaction, working_draft_id: str
    ) -> dict[str, Any] | None: ...
    def validation_run(self, tx: ReadTransaction, validation_id: str) -> dict[str, Any]: ...
    def artifact_versions(
        self, tx: ReadTransaction, application_id: str
    ) -> list[dict[str, Any]]: ...
    def artifact_version(self, tx: ReadTransaction, artifact_version_id: str) -> dict[str, Any]: ...
    def latest_decision(self, tx: ReadTransaction, application_id: str) -> dict[str, Any]: ...
    def recruitment_events(
        self, tx: ReadTransaction, application_id: str
    ) -> list[dict[str, Any]]: ...
    def submissions(self, tx: ReadTransaction, application_id: str) -> list[dict[str, Any]]: ...
    def audit_records(self, tx: ReadTransaction, application_id: str) -> list[dict[str, Any]]: ...
    def active_operation(
        self, tx: ReadTransaction, application_id: str
    ) -> OperationView | None: ...
    def latest_operation(
        self, tx: ReadTransaction, application_id: str
    ) -> OperationView | None: ...
    def has_active_matching_context_operation(
        self, tx: ReadTransaction, application_id: str
    ) -> bool: ...
