"""Typed command inputs and application-boundary outcomes.

Split by domain (prep / tracking / knowledge / shared) as siblings, matching
how `ports/` was already split from a single module. Re-exported here so
importers name one place, as they did when this was a single 751-line module.
"""

from __future__ import annotations

from ._base import BoundaryDTO, DuplicateMatchReason, WriteClient
from .knowledge import (
    ConfirmAndUseFactResult,
    FactAttachmentProfileTarget,
    FactAttachmentResult,
    FactAttachmentSectionTarget,
    FactAttachmentTargetsResult,
    FactDetailResult,
    FactEventView,
    FactHistoryResult,
    FactListItem,
    FactListResult,
    FactMutationResult,
    FactReconciliationResult,
    KnowledgeVersionsResult,
    fact_event_view,
)
from .prep import (
    AnalysisDecisionsResult,
    AnalysisResult,
    AnalyzeCommand,
    ApplyAnalysisDecisionsCommand,
    ApproveDocumentCommand,
    BuildFromAnalysisCommand,
    CheckDocumentCommand,
    ClaimAddition,
    ClaimPatch,
    DecisionMarkdownExport,
    DocumentCheckResult,
    DocumentMutationResult,
    DraftCommand,
    DraftContinuation,
    DraftResult,
    DuplicateCheckCommand,
    DuplicateCheckResult,
    DuplicateMatch,
    IngestCommand,
    IngestedApplication,
    RegenerateClaimCommand,
    RegenerateSectionCommand,
    RegenerationResult,
    RenderCommand,
    RenderResult,
    UpdateApplicationNotesCommand,
    UpdatedApplicationNotes,
    UpdatedJobText,
    UpdateDocumentCommand,
    UpdateJobTextCommand,
)
from .shared import ReconciliationResult
from .tracking import (
    ApplicationMutationResult,
    CloseApplicationCommand,
    DeleteApplicationCommand,
    ExternalSubmissionCommand,
    NextActionCommand,
    RecruitmentCorrectionCommand,
    RecruitmentStatusCommand,
    SubmissionCommand,
    SubmissionResult,
)

__all__ = [
    "BoundaryDTO",
    "WriteClient",
    "DuplicateMatchReason",
    "IngestCommand",
    "DuplicateCheckCommand",
    "UpdateJobTextCommand",
    "UpdateApplicationNotesCommand",
    "CloseApplicationCommand",
    "DeleteApplicationCommand",
    "AnalyzeCommand",
    "ApplyAnalysisDecisionsCommand",
    "BuildFromAnalysisCommand",
    "UpdateDocumentCommand",
    "CheckDocumentCommand",
    "ApproveDocumentCommand",
    "DocumentMutationResult",
    "DocumentCheckResult",
    "DraftCommand",
    "DraftContinuation",
    "RegenerateSectionCommand",
    "RegenerateClaimCommand",
    "ClaimPatch",
    "ClaimAddition",
    "RenderCommand",
    "RecruitmentStatusCommand",
    "RecruitmentCorrectionCommand",
    "SubmissionCommand",
    "ExternalSubmissionCommand",
    "NextActionCommand",
    "DuplicateMatch",
    "IngestedApplication",
    "DuplicateCheckResult",
    "UpdatedJobText",
    "AnalysisResult",
    "AnalysisDecisionsResult",
    "DraftResult",
    "RegenerationResult",
    "RenderResult",
    "ApplicationMutationResult",
    "UpdatedApplicationNotes",
    "SubmissionResult",
    "DecisionMarkdownExport",
    "KnowledgeVersionsResult",
    "FactEventView",
    "FactListItem",
    "FactListResult",
    "FactDetailResult",
    "FactHistoryResult",
    "FactMutationResult",
    "FactAttachmentSectionTarget",
    "FactAttachmentProfileTarget",
    "FactAttachmentTargetsResult",
    "FactAttachmentResult",
    "ConfirmAndUseFactResult",
    "FactReconciliationResult",
    "ReconciliationResult",
    "fact_event_view",
]
