"""Typed command inputs and application-boundary outcomes.

Split by domain (prep / tracking / knowledge / shared) as siblings, matching
how `ports/` was already split from a single module. Re-exported here so
importers name one place, as they did when this was a single 751-line module.
"""

from __future__ import annotations

from ._base import BoundaryDTO, DuplicateMatchReason, WriteClient
from .knowledge import (
    ConfirmAndUseFactResult,
    FactAttachmentProfileTarget,
    FactAttachmentResult,
    FactAttachmentSectionTarget,
    FactAttachmentTargetsResult,
    FactDetailResult,
    FactEventView,
    FactHistoryResult,
    FactListItem,
    FactListResult,
    FactMutationResult,
    FactReconciliationResult,
    KnowledgeVersionsResult,
    fact_event_view,
)
from .legacy import (  # temporary re-export: removed in Wave 3
    ApplySelectionChangeCommand,
    ApprovalResult,
    ApproveDraftCommand,
    ArchivedWorkingDraftResult,
    ArchiveWorkingDraftCommand,
    CreateSelectionPlanCommand,
    EditResult,
    ProposeSelectionPlanCommand,
    ReplaceWorkingDraftCommand,
    SelectionChangeResult,
    SelectionPlanResult,
    UpdateWorkingDraftCommand,
    ValidateDraftCommand,
    ValidationRunResult,
    WorkingDraftUpdateResult,
)
from .prep import (
    AnalysisDecisionsResult,
    AnalysisResult,
    AnalyzeCommand,
    ApplyAnalysisDecisionsCommand,
    ApproveDocumentCommand,
    BuildFromAnalysisCommand,
    CheckDocumentCommand,
    ClaimAddition,
    ClaimPatch,
    CreatedJobSnapshot,
    CreateJobSnapshotCommand,
    DecisionMarkdownExport,
    DocumentCheckResult,
    DocumentMutationResult,
    DraftCommand,
    DraftResult,
    DuplicateCheckCommand,
    DuplicateCheckResult,
    DuplicateMatch,
    IngestCommand,
    IngestedApplication,
    ProposeSelectionCommand,
    RegenerateClaimCommand,
    RegenerateSectionCommand,
    RegenerationResult,
    RenderCommand,
    RenderResult,
    SelectionOverlay,
    UpdateApplicationNotesCommand,
    UpdatedApplicationNotes,
    UpdateDocumentCommand,
    UpdateSelectionCommand,
)
from .shared import ReconciliationResult
from .tracking import (
    ApplicationMutationResult,
    CloseApplicationCommand,
    DeleteApplicationCommand,
    ExternalSubmissionCommand,
    NextActionCommand,
    RecruitmentCorrectionCommand,
    RecruitmentStatusCommand,
    SubmissionCommand,
    SubmissionResult,
)

__all__ = [
    "BoundaryDTO",
    "WriteClient",
    "DuplicateMatchReason",
    "IngestCommand",
    "DuplicateCheckCommand",
    "CreateJobSnapshotCommand",
    "UpdateApplicationNotesCommand",
    "CloseApplicationCommand",
    "DeleteApplicationCommand",
    "AnalyzeCommand",
    "SelectionOverlay",
    "CreateSelectionPlanCommand",
    "ApplyAnalysisDecisionsCommand",
    "ProposeSelectionPlanCommand",
    "ProposeSelectionCommand",
    "UpdateSelectionCommand",
    "BuildFromAnalysisCommand",
    "UpdateDocumentCommand",
    "CheckDocumentCommand",
    "ApproveDocumentCommand",
    "DocumentMutationResult",
    "DocumentCheckResult",
    "DraftCommand",
    "RegenerateSectionCommand",
    "RegenerateClaimCommand",
    "ClaimPatch",
    "ClaimAddition",
    "UpdateWorkingDraftCommand",
    "ApplySelectionChangeCommand",
    "ArchiveWorkingDraftCommand",
    "ReplaceWorkingDraftCommand",
    "ValidateDraftCommand",
    "ApproveDraftCommand",
    "RenderCommand",
    "RecruitmentStatusCommand",
    "RecruitmentCorrectionCommand",
    "SubmissionCommand",
    "ExternalSubmissionCommand",
    "NextActionCommand",
    "DuplicateMatch",
    "IngestedApplication",
    "DuplicateCheckResult",
    "CreatedJobSnapshot",
    "AnalysisResult",
    "SelectionPlanResult",
    "AnalysisDecisionsResult",
    "DraftResult",
    "EditResult",
    "WorkingDraftUpdateResult",
    "RegenerationResult",
    "SelectionChangeResult",
    "ArchivedWorkingDraftResult",
    "ValidationRunResult",
    "ApprovalResult",
    "RenderResult",
    "ApplicationMutationResult",
    "UpdatedApplicationNotes",
    "SubmissionResult",
    "DecisionMarkdownExport",
    "KnowledgeVersionsResult",
    "FactEventView",
    "FactListItem",
    "FactListResult",
    "FactDetailResult",
    "FactHistoryResult",
    "FactMutationResult",
    "FactAttachmentSectionTarget",
    "FactAttachmentProfileTarget",
    "FactAttachmentTargetsResult",
    "FactAttachmentResult",
    "ConfirmAndUseFactResult",
    "FactReconciliationResult",
    "ReconciliationResult",
    "fact_event_view",
]
